title: CityCamp
description: "CityCamp is a global movement of community-focused events that foster civic collaboration and innovation."
baseurl: ""
url: https://citycamp.com
email:

# Build settings
theme:
markdown: kramdown
plugins:
  - jekyll-datapage-generator
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  load_paths:
    - /home/runner/work/citycamp.github.io/citycamp.github.io/node_modules/bootstrap/scss
  style: compressed

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      folder: "Pages"
      img-path: "pages"
      parent: "pages"
      layout: "default"
      short: "false"
      schematype: ""
  - scope:
      path: "_posts"
      type: "posts"
    values:
      folder: "News"
      img-path: "posts"
      parent: "news"
      layout: "post"
      short: "true"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "profile"
  - scope:
      path: "_topics"
      type: "topics"
    values:
      folder: "Topics"
      layout: "topic"
      parent: "topics"
      short: "true"
  - scope:
      path: "_events"
      type: "events"
    values:
      folder: "Events"
      parent: "events"
      layout: "event"
      schematype: "Event"

# Collections
collections:
  pages:
    output: true
    permalink: :title
  posts:
    output: true
    permalink: /news/:title
  people:
    output: true
    permalink: people/:title
  topics:
    output: true
    permalink: /topics/:title

# Pagination
paginate: 12
paginate_path: "/news/page:num/"

# For jekyll-datapage-generator
# Generates /events/atlanta-ga pages for events.json records with a Status of "In progress"
page_gen:
  - data: events
    template: event
    dir: /events/
    index_files: true
    name_expr: "record['slug']"
    title: 'name'
    # filter_condition: "record['Status'] == 'In progress'"
